- hosts: localhost
  vars:
    PETCLINIC_VERSION: 0.0.1
  tasks:
  - name: install docker-py
    pip: name=docker-py version=1.2.1
    become: yes
    become_method: sudo
  - name: create docker folder
    file: state=directory path=/home/ec2-user/dock
  - name: creating Dockerfile from template
    template: src=/home/ec2-user/course/Dockerfile.j2 dest=/home/ec2-user/dock/Dockerfile
  - name: create image
    docker_image: path="/home/ec2-user/dock" name="petclin" state="present" tag="ll" 
