FROM centos:latest
MAINTAINER shimib
RUN yum install -y mc
RUN yum install -y java-1.8.0-openjdk-devel.x86_64
RUN yum install -y tomcat
RUN yum install -y which
RUN mkdir /logs
ENV NAME shimi
ADD http://52.58.29.27:8081/artifactory/libs-release-local/org/springframework/samples/spring-petclinic-FE/{{PETCLINIC_VERSION}}/spring-petclinic-FE-{{PETCLINIC_VERSION}}.war /usr/share/tomcat/webapps
CMD tomcat start && tail -F /logs/catalina.out
